name: Send Telegram Message

on:
  workflow_dispatch:  # Anh có thể chạy tay bằng nút Run workflow nè

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_MESSAGE: ${{ secrets.TELEGRAM_MESSAGE }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${TELEGRAM_MESSAGE}" \
            -d parse_mode="HTML"
